name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1